name: Build package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          chmod u+x scripts/build-package.sh
          scripts/build-package.sh